### ISSUE TITLE
Error: Client ID not registered Ketika Vostro Inquiry

### ISSUE THREAD

**Issue by B10715018** [bni-api/bni-python#9]
Siang kak, saya sudah berhasil menggunakan utility untuk get access token dengan credentials yang saya dapatkan melalui MyApplication di BNI developer website. Saya melakukan request dengan hit API melalui https://sandbox.bni.co.id:8066 dengan bahasa Golang. Namun ketika saya melakukan request ke endpoint lain seperti vostro inquiry, saya mendapatkan error client id not registered. Dan saya sudah memastikan bahwa My Application yang saya miliki sudah punya permission untuk remittance. Izin bertanya, apakah ada langkah yang saya salah lakukan atau ada yang saya miss ? Terima kasih untuk waktunya :)

**Comment by harismawan** [comment]
Siang kak, mohon pastikan kembali URL endpoint yg digunakan untuk hit request ya

Sandbox:
- Credentials didapat dari web developer BNI ([https://digitalservices.bni.co.id](https://digitalservices.bni.co.id))
- URL endpoint `https://sandbox.bni.co.id` (tanpa port)

Development:
- Credentials didapat dari tim integrasi BNI (bukan dari web developer BNI)
- URL endpoint `https://newapidev.bni.co.id:8066` (dengan port 8066)

Jika saya lihat dari kasus kakak, sepertinya kakak mendapatkan credentials dari web developer BNI ([https://digitalservices.bni.co.id](https://digitalservices.bni.co.id)), jadi URL yang digunakan adalah `https://sandbox.bni.co.id` (tanpa port) ya kak 😊

**Comment by B10715018** [comment]
Maaf kak, koreksi saya telah menggunakan url endpoint https://sandbox.bni.co.id tanpa port, dan client ID yang digunakan dari OAuth credential client ID yang di dapatkan dari web credentials. Namun masih mendapatkan response client ID not registered

Untuk pertanyaan selanjutnya, untuk Vostro Inquiry di Remittance apakah path `/remittance/vostroInquiry/{Client ID}`, apakah benar client ID yang digunakan adalah client ID dari OAuth Credential ?

**Comment by harismawan** [comment]
Maaf late response kak, untuk client id pada API Remittance diisi dengan nama aplikasi yang telah didaftarkan di web developer BNI [https://digitalservices.bni.co.id](https://digitalservices.bni.co.id) ya kak

contoh: /remittance/vostroInquiry/TESTAPP

**Comment by B10715018** [comment]
Baik terima kasih kak :)
